name: npm release

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://timbru31/java-node:latest
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn && yarn release && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
